data:
  csv_file: '/data/digbose92/ads_complete_repo/ads_codes/SAIM-ADS/data/SAIM_data/SAIM_multi_task_tone_soc_message_topic_data_no_zero_files.csv'
  transcript_file: '/data/digbose92/ads_complete_repo/ads_transcripts/combined_transcripts/en_combined_transcripts.json'
  base_folder: '/data/digbose92/ads_complete_repo/ads_features/shot_embeddings/clip_features_4fps/'

parameters:
  batch_size: 16
  train_shuffle: True
  val_shuffle: False
  test_shuffle: False
  epochs: 50
  early_stop: 5
  text_max_length: 35
  video_max_length: 512
  num_workers: 4
  task_name: 'Transition_val'

device:
  is_cuda: True

loss:
  loss_option: 'bce_cross_entropy_loss'

optimizer:
  choice: 'Adam'
  lr: 1e-4
  gamma: 0.95
  step_size: 15
  mode: 'max'
  decay: 0.001
  patience: 5
  factor: 0.5
  verbose: True

model:
  model_type: 'Perceiver_single_task_classifier_shot_level_multiple_seeds'
  text_dim: 768
  video_dim: 512
  dim: 128
  queries_dim: 256
  use_queries: False
  depth: 4
  num_latents: 16
  cross_heads: 1
  latent_heads: 8
  cross_dim_head: 32
  latent_dim_head: 32
  latent_dim: 256
  weight_tie_layers: False
  seq_dropout_prob: 0.1
  n_classes: 2
  batch_first: True
  model_name: 'bert-base-uncased'

output:
  model_dir: '/data/digbose92/ads_complete_repo/ads_codes/model_files/recent_models/multi_run_model_dir'
  log_dir: '/data/digbose92/ads_complete_repo/ads_codes/model_files/recent_models/multi_run_log_dir'
  multiple_run_folder: '/data/digbose92/ads_complete_repo/ads_codes/model_files/multi_run_folder'