wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: huggingface
    huggingface_version: 4.26.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.16
    start_time: 1676962502.347832
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.8.16
      5: 0.13.10
      6: 4.26.0
      8:
      - 5
data:
  desc: null
  value:
    csv_file: /data/digbose92/ads_complete_repo/ads_codes/SAIM-ADS/data/SAIM_ads_data_message_tone_train_test_val_clip_features.csv
device:
  desc: null
  value:
    is_cuda: true
loss:
  desc: null
  value:
    loss_option: bce_cross_entropy_loss
model:
  desc: null
  value:
    batch_first: true
    embedding_dim: 512
    model_type: LSTM
    n_classes: 2
    n_hidden: 512
    n_layers: 2
    option: LSTM_multi_layer_tone_transition_model
optimizer:
  desc: null
  value:
    choice: Adam
    decay: 0.001
    factor: 0.5
    gamma: 0.5
    lr: 1e-3
    mode: max
    patience: 5
    scheduler: step_lr
    step_size: 15
    verbose: true
output:
  desc: null
  value:
    log_dir: /data/digbose92/ads_complete_repo/ads_codes/model_files/recent_models/log_dir
    model_dir: /data/digbose92/ads_complete_repo/ads_codes/model_files/recent_models/model_dir
parameters:
  desc: null
  value:
    base_fps: 24
    batch_size: 16
    early_stop: 5
    epochs: 50
    fps: 4
    max_length: 333
    num_workers: 4
    train_shuffle: true
    val_shuffle: false
