data:
  csv_file: '/data/digbose92/ads_complete_repo/ads_codes/SAIM-ADS/data/SAIM_data/SAIM_multi_task_tone_soc_message_topic_data_no_zero_files.csv'
  topic_file: '/data/digbose92/ads_complete_repo/ads_codes/SAIM-ADS/data/topic_list_18.json'
  base_folder: '/data/digbose92/ads_complete_repo/ads_features/shot_embeddings/clip_features_4fps/'

parameters:
  batch_size: 16
  train_shuffle: True
  val_shuffle: False
  test_shuffle: False
  epochs: 50
  early_stop: 5
  max_length: 35
  num_workers: 1
  task_dict: {'Transition_val':2,'social_message':2}
  num_runs: 5

device:
  is_cuda: True

loss:
  weight_dict: {'Transition_val':0.45,'social_message':0.55}

optimizer:
  choice: 'AdamW'
  lr: 1e-4
  gamma: 0.5
  step_size: 15
  decay: 0.001
  patience: 5
  factor: 0.5
  verbose: True

model:
  model_type: 'MHA_attn_multi_task_classifier_CLIP_features_shot_level_multiple_seeds_focal_loss'
  input_dim: 512
  model_dim: 256
  num_heads: 4
  num_layers: 4
  input_dropout: 0.2
  output_dropout: 0.2
  model_dropout: 0.2
  n_classes: 18
  batch_first: True

output:
  model_dir: '/data/digbose92/ads_complete_repo/ads_codes/model_files/recent_models/multi_run_model_dir'
  log_dir: '/data/digbose92/ads_complete_repo/ads_codes/model_files/recent_models/multi_run_log_dir'
  multiple_run_folder: '/data/digbose92/ads_complete_repo/ads_codes/model_files/multi_run_folder'